### ISSUE TITLE
Update capacitor to new kvs hierarchy for jobs

### ISSUE THREAD

**Issue by grondo** [flux-framework/capacitor#6]
flux-framework/flux-core#811 changed the `lwj.` directory for jobs from a flat directory with all jobs in `lwj.ID` to a configurable hierarchy of directories, e.g. `lwj.x.y.ID`. There are just a few places in `flux-capacitor` that make an assumption that the job directory will be found in `lwj.id`:

```
flux-capacitor:        jobdir = 'lwj.{}'.format(job.job_id)
flux-capacitor:        m = re.match('lwj.(\d*).state', key)
flux-capacitor:                kvs.watch(fh, 'lwj.{}.state'.format(job_id), job_state_change, None)
flux-capacitor:                        prefix = 'lwj.{}.{}: '.format(job_id, task_id)
flux-capacitor:                    kz.attach(fh, 'lwj.{}.{}.stdout'.format(job_id, task_id), sys.stdout, prefix)
flux-capacitor:                    kz.attach(fh, 'lwj.{}.{}.stderr'.format(job_id, task_id), sys.stderr, prefix)
```

I'll take a stab at updating the script, but my changes will definitely require auditing by either @trws or @SteVwonder

**Comment by grondo** [comment]
Actually, does current capacitor even work with most recent `flux-core` python bindings? I'm getting an error from the import of `flux.kz` which doesn't seem to exist in the generated bindings. (I only see `flux._kz` module). It is probably just my lack of experience with python, @SteVwonder, @trws, I apologize if I'm just doing something dumb

``` sh
$ export FLUX_EXEC_PATH=$FLUX_EXEC_PATH:$(pwd)
$ flux capacitor 
Traceback (most recent call last):
  File "/g/g0/grondo/git/capacitor/flux-capacitor", line 21, in <module>
    import flux.kz as kz
ImportError: No module named kz

```

**Comment by trws** [comment]
It may not, I'll look into it as soon as I get a chance.  The kz binding should be built, but there could be a build system problem, _kz.py is the generated script that generates the .c file that provides the actual bindings, so having that and no _kz.so/kz.py is worrisome.  I'm in a bit of a bad spot for net access just now, if I haven't done it when you notice this, could someone assign this to me?

On October 19, 2016 at 3:21:33 PM PDT, Mark Grondona notifications@github.com wrote:

Actually, does current capacitor even work with most recent flux-core python bindings? I'm getting an error from the import of flux.kz which doesn't seem to exist in the generated bindings. (I only see flux._kz module). It is probably just my lack of experience with python, @SteVwonderhttps://github.com/SteVwonder, @trwshttps://github.com/trws, I apologize if I'm just doing something dumb

$ export FLUX_EXEC_PATH=$FLUX_EXEC_PATH:$(pwd)
$ flux capacitor
Traceback (most recent call last):
  File "/g/g0/grondo/git/capacitor/flux-capacitor", line 21, in <module>
    import flux.kz as kz
ImportError: No module named kz

##

**Comment by SteVwonder** [comment]
I don't have a good solution for kz, but the kvs watch can be replaced by JSC watches (see #5 and https://github.com/SteVwonder/capacitor/blob/runtime-prediction/flux-capacitor).

**Comment by SteVwonder** [comment]
@grondo: What are the current supported methods for determining the KVS directory of a job?  I know there is an RPC service that takes a job id and returns the kvs directory key.  My understanding is that this will not work for flux-capacitor since it is not a flux comms module and thus cannot perform an `rpc_get`.

**Comment by grondo** [comment]
@SteVwonder, there are a couple ways to get the kvs path to a job.

The RPC is `job.kvspath`, and you send a request for a list of jobids to translate with json of the form

``` json
{ "ids": [ id1, id2, ... ] }
```

The response will contain a list of corresponding paths

``` json
{ "paths": [ "path1", "path2", ...] }
```

You can read the json response in any of the supported RPC methods. Any user of the flux API should be able to use `rpc_get()` unless there is some limitation of which I'm not aware.

Also, the kvs path for a newly created job is sent in the reply to the `job.create` RPC, it is held in the `kvs_path` key. Also, all state events now include the `kvs_path` for the job on which the state is being reported.

Hope this helps, and sorry it isn't more clear!

**Comment by SteVwonder** [comment]
@grondo: the state events is perfect!

Based on a previous discussion with @garlick (which I'm having trouble finding), I was under the impression that only flux comms modules could receive RPCs.  Independent processes that run `flux_open` can send RPCs but not receive any responses.  I am probably misunderstanding/misremembering something though.

**Comment by grondo** [comment]
You are correct, only comms modules can receive rpcs because only they can register a "service" name with the broker, which I think is required to become the target of an RPC. 

However, I'm probably just misunderstanding the question because any API user can _send_ an RPC with `flux_rpc ()`,  then `flux_rpc_then ()` or `flux_rpc_get ()`, which is what you'd use from capacitor here to translate a jobid to a kvs path, e.g. see code added to [jstatctl.c](https://github.com/flux-framework/flux-core/blob/master/src/modules/libjsc/jstatctl.c#L178-L181).

**Comment by SteVwonder** [comment]
@grondo: ah, I see.  Thanks for the clarification!

**Comment by grondo** [comment]
No problem, if you need any help let me know. I feel a bit bad that I broke capacitor and didn't fix it...

**Comment by trws** [comment]
As a note here, I'm working through this problem in my ATS backend right now, and in principle the kvs_path also comes back in the job creation response.  It looks like that isn't there in the currently installed release version on TOSS2, but that's probably the way to get it for capacitor and similar.

**Comment by trws** [comment]
Found the issue with KZ also by the way, it's getting built just fine but I made a mistake with the automake setup such that it doesn't get installed.  Putting up a PR for that momentarily.

**Comment by grondo** [comment]
Yeah, release 0.5.0 will have the required changes. An RPM is built, but
likely not installed yet. I should also kick off a build of latest
flux-sched RPM too..
